/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {

        return true;
    }
    public void restaurantRating(){
        Restaurant myRest = new Restaurant("Yousef",3,3);
        myRest.toString();
    }
}
