/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

}
class RestaurantTest{
    @Test void restaurantConstructorTest() {
        Restaurant restTest = new Restaurant("Yousef", 3,3);
        assertEquals(restTest.getName(), "Yousef");
    }
    @Test void restaurantRatingReturnsString() {
        Restaurant restTest = new Restaurant("Yousef Salem", 3,3);
        assertEquals(restTest.toString(), "This restaurant's name is Yousef, it has a 3 star rating, and it's prices $$$");
    }
}

class ReviewTest {
    @Test void reviewConstructorTest() {
        Review restTest = new Review("A review", "Yousef Salem",3);
        assertEquals(restTest.getAuthor(), "Yousef Salem");
    }
    @Test
    void reviewReturnsString() {
        Review restTest = new Review("I love it!!!", "Yousef Salem", 4);
        assertEquals(restTest.toString(), "Author's name is Yousef Salem, He has reviewed this restaurant with  4 star rating, and he said \" I love it!!! \"");
    }
}